language: java
jdk:
- oraclejdk8
env:
  global:
  - SONATYPE_USERNAME=leonarduk
  - secure: k+KMswNpvdSHeC9gIfASvSiF6D0ad+Ear8fZtvngdwAXcZFRik6FI3tUy/QQHSgeIE+7AJ6KnNJZ0ZBGPdc6C50idu7hmHQ7K4/24e+KSSBistU8ifSvLrkm1yUJz8ta9HBPpN3fPhmXRjA1kOUW5C8wo5uLTm+0tUyJBRcexxOmyuf5rKvbEGD9YnKDnr3VEZ4ZfzLAoWqgm4SW4nI0vNr9leKfRSAhOVzXflHi8XJAoMZYE3dUyhhPy2PoqgKSk1LHsEOwezl2/5CRSz6tu1rSVwFAy3YaSSok5J7jXI20hs5edG/9Dn04j6HZn+B+NWEEhcog4d/SXGMQIqW6MT8pjHE1/r05G0IZuhOgI83DzcUEEn3YaQXBbHwM9neBcKLJjXU4Z71AEqTwKpzFBgisXSj6cEfXVfp0DTRFSnWyB4gmbyObY3aKDR/r8Df1oqLXxkCZo9LFNRHBlETni3IXH5KsnOQDNJxIA6OuKsVdm8bFHhQ7z8S50kjfAn7J9VhEFAbQ7TbwHIllpb2ubRzBKylkv/3wtwvEt3y+KfUsbyeKgAA/qYd5YOEmbICp4qoS4MTFH9OZuehxzy+ZLLSDom6byLJYEeW5QJSF6MBh5i4Bkqs6AK76ZZBusOTI9rrOYPi9r/45fM23QSW0NX36arqAQK+STdh3dkwoSus=
script: mvn clean verify
after_success:
- bash <(curl -s https://codecov.io/bash)
- mvn deploy --settings travis-settings.xml -DskipTests=true -B
